### ISSUE TITLE
VOC and SBD are not enough for training?

### ISSUE THREAD

**Issue by y0un5** [visinf/1-stage-wseg#2]
Thank you for sharing great work!

I've followed README, but got the following error.

```
$ sh ./launch/run_voc_resnet38.sh
python train.py --dataset pascal_voc --cfg configs/voc_resnet38.yaml --exp baselines --run v01
LOG: logs/pascal_voc/baselines/v01.log
Config:
 {'NUM_GPUS': 1, 'TRAIN': {'BATCH_SIZE': 16, 'NUM_EPOCHS': 24, 'NUM_WORKERS': 8, 'MASK_LOSS': 0.0, 'PRETRAIN': 5}, 'TEST': {'METHOD': 'multiscale', 'DATA_ROOT': '/fastdata/naraslanov', 'SCALES': [1, 0.5, 1.5, 2.0], 'FLIP': True, 'PAD_SIZE': [1024, 1024], 'CROP_SIZE': [448, 448], 'CROP_GRID_SIZE': [2, 2], 'BATCH_SIZE': 8, 'BG_POW': 3, 'USE_GT_LABELS': False, 'FP_CUT_SCORE': 0.1}, 'DATASET': {'CROP_SIZE': 321, 'SCALE_FROM': 0.9, 'SCALE_TO': 1.0, 'PATH': 'data/images'}, 'NET': {'MODEL': 'ae', 'BACKBONE': 'resnet38', 'PRE_WEIGHTS_PATH': './models/weights/ilsvrc-cls_rna-a1_cls1000_ep-0001.pth', 'OPT': 'SGD', 'LR': 0.001, 'BETA1': 0.5, 'MOMENTUM': 0.9, 'WEIGHT_DECAY': 0.0005, 'LOSS': 'SoftMargin', 'MASK_LOSS_BCE': 1.0, 'BG_SCORE': 0.1, 'FOCAL_P': 3, 'FOCAL_LAMBDA': 0.01, 'PAMR_KERNEL': [1, 2, 4, 8, 12, 24], 'PAMR_ITER': 10, 'SG_PSI': 0.3}, 'MASKS': {'CRF': {'ALPHA_LOW': 4, 'ALPHA_HIGH': 32}}, 'CUDA': False, 'DEBUG': False, 'PYTORCH_VERSION_LESS_THAN_040': False}
Traceback (most recent call last):
  File "train.py", line 318, in <module>
    trainer = DecTrainer(args)
  File "train.py", line 47, in __init__
    self.valloader = get_dataloader(args, cfg, 'val')
  File "/home1/irteam/work/yjkim/Project/1-stage-wseg/datasets/__init__.py", line 19, in get_dataloader
    dataset = dataset_cls(cfg, split, test_mode)
  File "/home1/irteam/work/yjkim/Project/1-stage-wseg/datasets/pascal_voc.py", line 138, in __init__
    assert os.path.isfile(_mask), '%s not found' % _mask
AssertionError: ./data/voc/VOCdevkit/VOC2012/SegmentationClassRaw/2007_007881.png not found
```

I can't find `SegmentationClassRaw` directory in VOC and SBD. Could you explain how to get these files?

**Comment by arnike** [comment]
Hi @y0un5,

thanks for reporting this. Using the original VOC files from SegmentationClass/ should be equivalent: these are the same files but without the colour indexing. I'll update the file lists.

Best,
Nikita
