### ISSUE TITLE
stuck on epoch 0

### ISSUE THREAD

**Issue by SharhadBashar** [visinf/1-stage-wseg#24]
Why do we enter validation on epoch 0?
And how long does each epoch take?
I have been stuck on epoch 0, in the validation function for 5+ hours

**Comment by arnike** [comment]
Hi,
something is clearly amiss, because the complete training should be done in about 6 hours. Could you track down where the process gets stuck? What's your configuration (PyTorch, CUDA/CuDNN version, the number of GPUs)?

**Comment by SharhadBashar** [comment]
these are the versions outside the environment:
pytorch-1.4.0
Cuda compilation tools, release 10.1, V10.1.243
cudnn-7.6.5
I have one gpu: 3090. but if thats the issue, i can easily add another one with sli

if i create the environment using conda activate one_stage, where i installed everything in the requirments.txt i have:
pytorch-1.0.1
Cuda compilation tools, release 10.1, V10.1.243

I first create the environment by using: conda activate one_stage
Then i run bash ./launch/run_voc_resnet38.sh
According to the code in train.py:
DEBUG is False, so log_int = 2
epoch % log_int is 0, so it enters that if statement
if not DEBUG is true, so it runs this line: 
`time_call(trainer.validation,` "Validation / Train: ", epoch, trainer.writer, trainer.trainloader_val)` and enters the validation function and is stuck there

All i see on the screen is the model architecture, the configs and Epoch >>> 0 and its just stuck there

**Comment by arnike** [comment]
Hi,
the setup seems fine, it should train.

`time_call(trainer.validation, "Validation / Train: ", epoch, trainer.writer, trainer.trainloader_val)`
This line calls trainer.validation, so where is it stuck there? Do you observe any GPU utilisation?

**Comment by SharhadBashar** [comment]
Hi, yes there is gpu utilization. I can see it using nvdia-smi

I put print statements inside `def validation` to see how far it goes
it enters the function validation
it runs the line `stat = StatManager()`
then it runs `self.enc.eval()`
It creates the lists for targets_all and preds_all
but it never enters the for loop `for n, (image, gt_labels, _) in enumerate(loader):` 
i even print out the loader : `<torch.utils.data.dataloader.DataLoader object at 0x7ff1247e58d0>`

**Comment by SharhadBashar** [comment]
here are the things that are printed before epoch 0 (i turned off printing the model)
`Config: 
 {'NUM_GPUS': 1, 'TRAIN': {'BATCH_SIZE': 16, 'NUM_EPOCHS': 24, 'NUM_WORKERS': 8, 'MASK_LOSS': 0.0, 'PRETRAIN': 5}, 'TEST': {'METHOD': 'multiscale', 'DATA_ROOT': '/fastdata/naraslanov', 'SCALES': [1, 0.5, 1.5, 2.0], 'FLIP': True, 'PAD_SIZE': [1024, 1024], 'CROP_SIZE': [448, 448], 'CROP_GRID_SIZE': [2, 2], 'BATCH_SIZE': 8, 'BG_POW': 3, 'NUM_CLASSES': 21, 'USE_GT_LABELS': False, 'FP_CUT_SCORE': 0.1}, 'DATASET': {'CROP_SIZE': 321, 'SCALE_FROM': 0.9, 'SCALE_TO': 1.0, 'PATH': 'data/images'}, 'NET': {'MODEL': 'ae', 'BACKBONE': 'resnet38', 'PRE_WEIGHTS_PATH': './models/weights/ilsvrc-cls_rna-a1_cls1000_ep-0001.pth', 'OPT': 'SGD', 'LR': 0.001, 'BETA1': 0.5, 'MOMENTUM': 0.9, 'WEIGHT_DECAY': 0.0005, 'LOSS': 'SoftMargin', 'MASK_LOSS_BCE': 1.0, 'BG_SCORE': 0.1, 'FOCAL_P': 3, 'FOCAL_LAMBDA': 0.01, 'PAMR_KERNEL': [1, 2, 4, 8, 12, 24], 'PAMR_ITER': 10, 'SG_PSI': 0.3}, 'MASKS': {'CRF': {'ALPHA_LOW': 4, 'ALPHA_HIGH': 32}}, 'CUDA': False, 'DEBUG': False, 'PYTORCH_VERSION_LESS_THAN_040': False}
Backbone: ResNet38
Model: AE
Loading weights from:  ./models/weights/ilsvrc-cls_rna-a1_cls1000_ep-0001.pth
Group 0: #35, LR=1.000e-03
Group 1: #0, LR=2.000e-03
Group 2: #26, LR=1.000e-02
Group 3: #13, LR=2.000e-02
Using SGD >>> learning rate = 1.000e-03, momentum = 9.000e-01, weight decay = 5.000e-04
`

**Comment by arnike** [comment]
It seems the workers in dataloader do not load/provide the data. Things to check:
- if you comment out the validation steps, does the training-time dataloader work?
- does the data loading step [here](https://github.com/visinf/1-stage-wseg/blob/cfe5784f9905d656e0f15fba0e6eb76a3731d80f/datasets/pascal_voc.py#L157) work standalone?
- another test is to set the number of workers in the dataloader (`num_workers`) to 0, which load the data in the main process.

**Comment by SharhadBashar** [comment]
1. I commented out the validation step in the for loop in the main, so the first thing that is called is:
`time_call(trainer.train_epoch, "Train epoch: ", epoch)`
Once again it enters `train_epoch` function
runs `self.enc.train()`, `stat = StatManager()`, `timer = Timer("New Epoch: ")` and `train_step = partial(self.step, train=True, visualise=False)`, but does not enter the for loop

2. i use the following two lines: 
`trainloader = VOCSegmentation(cfg, 'train', test_mode=None)
print(trainloader.__dict__)` 
and run that it prints a huge list of all the images so that working fine
and when i run `print(trainloader[0])` it does go inside the __getitem()__ and returns a tensor of the image

3. in datasets/__init__.py, i set this line to `kwargs = {'num_workers': 0, 'pin_memory': True}`
And that seems to run everything, but now i have a different issue. The validation works, and then it enters training. 
This is what is prints: `Loss [0000]: loss_cls: 323176.7500 | loss_fg: 0.0410 | loss_mask: 455.2327 | loss: 323176.7500 |  | Im/Sec: 0.0`
but after that, all losses are nan:
`Loss [0010]: loss_cls: nan | loss_fg: nan | loss_mask: 0.0000 | loss: nan |  | Im/Sec: 8.7`

**Comment by arnike** [comment]
Thanks. I suspect that there is indeed a multi-processing issue in the dataloader.
Are you working with Pascal VOC or some custom dataset? Did you modify any parts of the code or dataset filelists (git diff would be helpful)? Can you load all the files from the filelists using a standalone code? Are you on Linux?

**Comment by SharhadBashar** [comment]
i made no modifications to your code. I downloaded the Pascal VOC dataset and the other dataset with 10000+ images. I followed all the instructions in the readme file of this git. I am on ubuntu 
What exactly do you mean load all the files from the file list?

**Comment by arnike** [comment]
I have just tested the code in a single GPU setting and did not encounter these issues. I used a higher CUDA/PyTorch version, though (11.0/1.8), because I do not have a high capacity GPU with CUDA 10.1 at the moment.
Did you test that your PyTorch installation is working?
In the initial stages of the training (the first 5 epochs), there is really nothing fancy happening, the net is simply trained for multi-label classification. So, the exploding loss values you posted may be either due to the data loading incorrectly, or incorrect computation of the forward pass.

**Comment by SharhadBashar** [comment]
is there anything i can do or any tests i can run? or if you have some time maybe we can chat live to figure out what going wrong? that would be really helpful

**Comment by SharhadBashar** [comment]
can you tell me what the versions of everything in your requirments.txt is?
Because when i try to create an environment with the following, i get a lot of incompatibility issues:
`
python=3.6.3
numpy=1.15.4
pillow=5.4.1
pydensecrf=1.0rc3
pytorch=1.8
pyyaml=3.13
torchvision=0.2.1
tqdm==4.31.1
tensorboardX=1.6
packaging=19.0
scikit-learn=0.20.2
scikit-image=0.16.1
six=1.12.0
scipy=1.2.1
`

**Comment by SharhadBashar** [comment]
Is there any other check I can do to find the cause of the error? i really need to get it running for my thesis

**Comment by SharhadBashar** [comment]
so i set num_worker to zero, and ran it again, and i am getting a new error:
'Traceback (most recent call last):
  File "train.py", line 334, in <module>
    time_call(trainer.validation, "Validation / Train: ", epoch, trainer.writer, trainer.trainloader_val)
  File "train.py", line 324, in time_call
    func(*args, **kwargs)
  File "train.py", line 260, in validation
    aps = average_precision_score(targets_stacked, preds_stacked, average=None)
  File "/home/s2bashar/anaconda3/envs/one_stage/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 241, in average_precision_score
    average, sample_weight=sample_weight)
  File "/home/s2bashar/anaconda3/envs/one_stage/lib/python3.6/site-packages/sklearn/metrics/base.py", line 81, in _average_binary_score
    y_score = check_array(y_score)
  File "/home/s2bashar/anaconda3/envs/one_stage/lib/python3.6/site-packages/sklearn/utils/validation.py", line 573, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/home/s2bashar/anaconda3/envs/one_stage/lib/python3.6/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
'

**Comment by SharhadBashar** [comment]
Hi
I sent you a detailed email with all the information based on your suggestions. Please get back to me as soon as you can
Thanks
