### ISSUE TITLE
an illegal memory access was encountered

### ISSUE THREAD

**Issue by leoshine** [visinf/1-stage-wseg#3]
Error

```
Using SGD >>> learning rate = 5.000e-04, momentum = 9.000e-01, weight decay = 5.000e-04
Epoch >>>  0
[iter] 0  torch.Size([16, 3, 448, 448]), torch.Size([16, 20])
Traceback (most recent call last):
  File "train.py", line 335, in <module>
    time_call(trainer.validation, "Validation / Train: ", epoch, trainer.writer, trainer.trainloader_val)
  File "train.py", line 325, in time_call
    func(*args, **kwargs)
  File "train.py", line 249, in validation
    cls_raw, masks_all, mask_logits = eval_batch(image, gt_labels)
  File "train.py", line 226, in eval_batch
    self.step(epoch, image, gt_labels, train=False, visualise=False)
  File "train.py", line 89, in step
    cls_out, cls_fg, masks, mask_logits, pseudo_gt, loss_mask = self.enc(image, image_raw, gt_labels)
  File "anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 156, in forward
    return self.gather(outputs, self.output_device)
  File "anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 168, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "anaconda3/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "anaconda3/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "anaconda3/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "anaconda3/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 68, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "anaconda3/lib/python3.7/site-packages/torch/cuda/comm.py", line 165, in gather
    return torch._C._gather(tensors, dim, destination)
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered (insert_events at /opt/conda/conda-bld/pytorch_1587428398394/work/c10/cuda/CUDACachingAllocator.cpp:771)

```

Tracing back, it seems "gt_labels" in this line has problem:
https://github.com/visinf/1-stage-wseg/blob/1799c40ee59a3a180b1e7a3e164857664b09505e/train.py#L92

Just printing "gt_labels" before this line will also trigger the problem.

**Comment by arnike** [comment]
Hi @leoshine,

I haven't seen this before. Could you, please, provide a bit more details:
- PyTorch and CUDA versions;
- number and model of the GPUs you're running it on.

Thanks.
