### ISSUE TITLE
SBD conversion script missing?

### ISSUE THREAD

**Issue by ErikStammes** [visinf/1-stage-wseg#9]
I'm trying to run your code but I'm running into the following issue:
```Creating directory logs/pascal_voc/baseline
python train.py --dataset pascal_voc --cfg configs/voc_resnet38.yaml --exp baseline --run v01
LOG: logs/pascal_voc/baseline/v01.log
Config: 
 {'NUM_GPUS': 1, 'TRAIN': {'BATCH_SIZE': 16, 'NUM_EPOCHS': 24, 'NUM_WORKERS': 8, 'MASK_LOSS': 0.0, 'PRETRAIN': 5}, 'TEST': {'METHOD': 'multiscale', 'DATA_ROOT': '/fastdata/naraslanov', 'SCALES': [1, 0.5, 1.5, 2.0], 'FLIP': True, 'PAD_SIZE': [1024, 1024], 'CROP_SIZE': [448, 448], 'CROP_GRID_SIZE': [2, 2], 'BATCH_SIZE': 8, 'BG_POW': 3, 'USE_GT_LABELS': False, 'FP_CUT_SCORE': 0.1}, 'DATASET': {'CROP_SIZE': 321, 'SCALE_FROM': 0.9, 'SCALE_TO': 1.0, 'PATH': 'data/images'}, 'NET': {'MODEL': 'ae', 'BACKBONE': 'resnet38', 'PRE_WEIGHTS_PATH': './models/weights/ilsvrc-cls_rna-a1_cls1000_ep-0001.pth', 'OPT': 'SGD', 'LR': 0.001, 'BETA1': 0.5, 'MOMENTUM': 0.9, 'WEIGHT_DECAY': 0.0005, 'LOSS': 'SoftMargin', 'MASK_LOSS_BCE': 1.0, 'BG_SCORE': 0.1, 'FOCAL_P': 3, 'FOCAL_LAMBDA': 0.01, 'PAMR_KERNEL': [1, 2, 4, 8, 12, 24], 'PAMR_ITER': 10, 'SG_PSI': 0.3}, 'MASKS': {'CRF': {'ALPHA_LOW': 4, 'ALPHA_HIGH': 32}}, 'CUDA': False, 'DEBUG': False, 'PYTORCH_VERSION_LESS_THAN_040': False}
Traceback (most recent call last):
  File "train.py", line 318, in <module>
    trainer = DecTrainer(args)
  File "train.py", line 45, in __init__
    self.trainloader = get_dataloader(args, cfg, 'train')
  File "/home/stammes/development/1-stage-wseg/datasets/__init__.py", line 19, in get_dataloader
    dataset = dataset_cls(cfg, split, test_mode)
  File "/home/stammes/development/1-stage-wseg/datasets/pascal_voc.py", line 138, in __init__
    assert os.path.isfile(_mask), '%s not found' % _mask
AssertionError: ./data/sbd/benchmark_RELEASE/dataset/cls_png/2008_007573.png not found
```

The original dataset only contains the /sbd/benchmark_RELEASE/dataset/cls/*.mat folder. Looks like you converted those to .png, is there a script to do this somewhere?

Thanks!

**Comment by arnike** [comment]
Hi,
I've written the conversion code here: https://gist.github.com/arnike/9c671e5f56f4c6b2a30791773aa70f1d.
You can run it as:
```bash
python convert_sbd.py --inp [SBD_DIR/dataset/cls] --out [SBD_DIR/dataset/cls_png]
```
Let me know if that works for you. I'll add it to the repo then.

Best,
Nikita

**Comment by ErikStammes** [comment]
Thanks for the fast reply! The script works and I'm able to start training the model now.

**Comment by SharhadBashar** [comment]
Hi ErikStammes
Do you know how long each epoch takes? I have been running it for 5 hours, and its still stuck on epoch 0
